### ISSUE TITLE
Shouldn't the Library Close the File When Done?

### ISSUE THREAD

**Issue by pacarvalho** [extrame/xls#33]
I have been using this library and it seems to work as expected on MacOSX. However, If I cross compile and run my final program on Windows 7 32 bits, I run into a problem where XLS files that I open with this library cannot be edited by other programs. 

Example: If I open an XLS file using my software (unless I quit my software) I am unable to edit the file from Excel. 

I think this could be solved by exporting a `xls.Close` that would allow me to `defer xls.Close()` so that the file is closed once I am done with it. Does this make sense?

**Comment by extrame** [comment]
I agree.

But you know xls keep reading content from file in almost the whole process. First it get a reference table from file and until you try to read a line or another, It just start pulling the true content from file.

It work like xls file is a disk, I don’t think try to open a xls file in two software concurrently is a good idea.

And Reading the whole file into memory is being proven A BAD IDEA in library level, because performance is still the top1 requirement.

So I decide to add a Method named OpenWithCloser, it will return the workbook pointer and the io.Closer to you, you can decide when to close it.

And if your xls file is not so big, you can try using bytes.Reader to read the file into memory first, then close file an use xls.OpenReader to read it normally,

在 2018年3月19日，01:07，Paulo <notifications@github.com<mailto:notifications@github.com>> 写道：


I have been using this library and it seems to work as expected on MacOSX. However, If I cross compile and run my final program on Windows 7 32 bits, I run into a problem where XLS files that I open with this library cannot be edited by other programs.

Example: If I open an XLS file using my software (unless I quit my software) I am unable to edit the file from Excel.

I think this could be solved by exporting a xls.Close that would allow me to defer xls.Close() so that the file is closed once I am done with it. Does this make sense?

**Comment by pacarvalho** [comment]
Having this **OpenWithCloser** method would be very useful! The reason I need to close the file is that my program runs as a service and reads from files added to a directory. So if my program never closes the files then, even though it will be done reading from the files and will never touch them again, other programs are unable to use the files. 

With the method you proposed I can read the file then, once I am done, I can close the file and move on.
